services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - "node_modules:/app/node_modules"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
      - VITE_STUN_TURN_URL=turn:coturn:3478
      - VITE_STUN_TURN_USERNAME=base
      - VITE_STUN_TURN_CREDENTIAL=base
    develop:
      watch:
        - action: sync
          path: ./front-end
          target: /app
          ignore:
            - ./frontend/node_modules
        - action: rebuild
          path: ./front-end/package.json

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - "go_cache:/root/.cache/go-build"
    environment:
      - STUN_TURN_URL=turn:coturn:3478
      - STUN_TURN_USERNAME=base
      - STUN_TURN_CREDENTIAL=base
    develop:
      watch:
        - action: rebuild
          path: ./api

  coturn:
    image: coturn/coturn
    volumes:
      - "./turnserver.conf:/etc/coturn/turnserver.conf"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  node_modules:
  go_cache: